# I/O Configuration
input_dir: ${EXATRKX_DATA}/train_all
output_dir: ${SCRATCH}/run/feature_store

n_files: 100000
n_workers: 64
n_tasks: 1
overwrite: False
chunksize: 10

noise: True
skewed: False
layerwise: True             # True Edge List
modulewise: True            # True Edge List
inputedges: True            # Input Edge List

# if inputedges=True:
# then 'edge_index' will be built in the Processing stage, so one can use GNN stage right after that i.e. skipping Embedding & Filtering

# if inputedges=False:
# ithen 'edge_index' will be skipped in the Processing stage. Which means one should either build `edge_index` explicitly or may go through
# the Embedding and/or filtering stages. To use GNN stage, one needs in input data containing `edge_index` variable which is input to GNN.
