# Input/output configuration
input_dir: ${EXATRKX_DATA}/run_quick/feature_store
output_dir: ${EXATRKX_DATA}/run_quick/dnn_processed
project: DNNStudy
edge_cut: 0.5

# Dataset parameters
pt_signal_min: 0.
pt_background_min: 0.
datatype_names: [[train, val, test]]
datatype_split: [[8000, 1000, 1000]]

train_split: [[8000, 1000, 1000]]     # ADAK: for data_utils.py
sorted_events: True

noise: False
overwrite: True

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
aggregation: sum_max
hidden_activation: ReLU
weight: 2
warmup: 200
lr: 0.001
factor: 0.3
patience: 10
regime: [[pid]] # NOTE: [pid] assumes filtering has (not) been performed i.e. variable y_pid (y) exists in Data.
max_epochs: 10

# Post-processing
callbacks: [[GNNBuilder,GNNTelemetry]]
