# This example file contains all available options for the processing stage with short descriptions.
# Optional fields are marked with a # Optional comment.

# Input directory with the .csv files
# input_dir  : /home/nikin105/mlProject/data/machineLearning/mum5mup5/root/mlData.root
input_dir  : /home/nikin105/mlProject/data/machineLearning/mum5mup5/csv

# Output directory for the pyTorch geometry files
output_dir : /home/nikin105/mlProject/data/machineLearning/mum5mup5/newLayerwise

# - Parallelization parameters - 
overwrite : True  # ?
n_files   : 20    # ?
n_workers : 5     # ?
n_tasks   : 1     # ?
chunksize : 1     # ?

# - Graph construction method -
layerwise   : False # If True, construct true edges by connecting hits in adjacent layers. The radial distance to the interaction point must increase in every step.
modulewise  : False # If True, construct true edges by connecting hits in adjacent modules. The radial distance to the interaction point must increase or be the same in every step.
timeOrdered : True # If True, construct true edges by connecting hits sequentially in time. 

inputedges : newLayerwise # Method how the input edges are constructed. Options: 'layerwise' and 'all'

# - Filter -
noise     : False # ?
skewed    : True  # If True, include skewed layers for the graph construction.
filtering : True  # If True, get input edges without adjacent sectors
selection : False # ?