stage_list:
    #- {set: data_processing, name: TrackMLFeatureStore, config: prepare_alldata.yaml, batch_config: configs/batch_cpu_default.yaml, batch_setup: False}
    #- {set: edge_labelling, name: CheckResGCN, config: train_alldata_GCN.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: False, resume_id: }
    #- {set: edge_labelling, name: CheckResAGNN, config: train_alldata_AGNN.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: False, resume_id: }
    #- {set: edge_labelling, name: InteractionGNN, config: train_alldata_IGNN.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: True, resume_id: }
    #- {set: edge_labelling, name: EdgeClassifier, config: train_alldata_DNN.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: True, resume_id: }
    #- {set: graph_segmenting, name: TrackMLSegment, config: segment_alldata.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: False, resume_id:}
    
    # Comprehensive Example:
    #- {set: edge_labelling, name: InteractionGNN, config: train_alldata_GNN.yaml, batch_config: configs/batch_gpu_default.yaml, batch_setup: True, resume_id: , override: {callbacks: [GNNBuilder], edge_cut: 0.15, datatype_split: [2700, 100, 100]} }

